### ISSUE TITLE
Help Wanted - Is it possible to Deploy to Multiple Application Instances using this Action Script

### ISSUE THREAD

**Issue by muhammedshiffin** [roelmagdaleno/cloudways-api-git-pull-action#8]
Am trying to figure out whether I can trigger deployment to multiple applications using this.
I have 4 application instances from a single git-repo and I'd like to utilize Actions to automate deployments to these.

Thanks

**Comment by roelmagdaleno** [comment]
Hey @muhammedshiffin I've never done that before but I think is possible. Maybe you can create multiple steps that points to your specific server, apps and deploy paths.

For example:

```yaml
name: Cloudways API Git Pull

on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New Tag

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Instance 1 Cloudways API Git Pull
        uses: roelmagdaleno/cloudways-api-git-pull-action@stable
        with:
          email: ${{ secrets.CLOUDWAYS_EMAIL }}
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          server-id: 123
          app-id: 123
          branch-name: ${{ secrets.CLOUDWAYS_BRANCH_NAME }}
          deploy-path: ../public_html/instance_1

     - name: Instance 2 Cloudways API Git Pull
        uses: roelmagdaleno/cloudways-api-git-pull-action@stable
        with:
          email: ${{ secrets.CLOUDWAYS_EMAIL }}
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          server-id: 123456
          app-id: 123456
          branch-name: ${{ secrets.CLOUDWAYS_BRANCH_NAME }}
          deploy-path: ../public_html/instance_2
```

See what I mean? You just have to set your server and app ids with their respective deploy paths.
